CLASS zcx_vmd_no_extension DEFINITION
  PUBLIC
  INHERITING FROM cx_static_check
  CREATE PUBLIC  .

  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS zcx_vmd_no_extension IMPLEMENTATION.
ENDCLASS.
